### ISSUE TITLE
Linting workflow: Language/ecosystem support

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/.github#7]
#6 will add an initial reusable linting workflow. Here are some of the languages/ecosystems we'd like to eventually support:

- [x] Go (#6)
- [x] Rust (#6)
- [x] Python via `make lint` (#6)
- [ ] C and C++
  - [ ] CMake via `cmake-format`
- [ ] Ethereum (maybe?)
- [ ] Haskell (maybe?)
- [x] Generic `make lint` (#6)
- [ ] Ruby (maybe?)
- [x] Markdown linting with `markdownlint-cli` + `markdown-link-check` (#12)
  - [ ] Possible follow-on for `markdown-link-check`

**Comment by woodruffw** [comment]
For Markdown: it looks like https://github.com/DavidAnson/markdownlint-cli2-action might be a reasonable integration choice.

Example workflow: https://github.com/DavidAnson/markdownlint-cli2-action/blob/main/.github/workflows/example.yml
